### ISSUE TITLE
This version broke my MKDocs from Obsidian

### ISSUE THREAD

**Issue by Pageboy** [blueswen/mkdocs-glightbox#19]
With this update I get "AttributeError: 'NoneType' object has no attribute 'group'" in my deploy to Github Pages

**Comment by blueswen** [comment]
Could you please provide more detailed logs and share your code or a reproducible example to help me better understand the issue?

**Comment by Pageboy** [comment]
At this point:

Run mkdocs gh-deploy --force
  mkdocs gh-deploy --force
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.11.3/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.11.3/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.3/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.3/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.3/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.11.3/x64/lib

Then.....

ERROR    -  Error reading page 'eBookProduction/Enhancing an eBook with interactivity, multimedia and animation.md': 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.3/x64/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/opt/hostedtoolcache/Python/3.11.3/x64/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^

etc etc then......

AttributeError: 'NoneType' object has no attribute 'group'
Error: Process completed with exit code 1.

------

I have fixed this by using: - run: pip install mkdocs-glightbox==0.3.2

**Comment by 1871fotc** [comment]
I have experienced this also. Thanks for the workaround and thanks for Glightbox.

**Comment by yirooh** [comment]
I also got the same error when excecuting `mkdocs build`. The error log is:
```
Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/mkdocs/__main__.py", line [250](https://gitlab.wistron.com/ccoe/ea-guidebook/-/jobs/1707977#L250), in build_command
    build.build(cfg, dirty=not clean)
  File "/usr/local/lib/python3.8/site-packages/mkdocs/commands/build.py", line 308, in build
    _populate_page(file.page, config, files, dirty)
  File "/usr/local/lib/python3.8/site-packages/mkdocs/commands/build.py", line 184, in _populate_page
    page.content = config.plugins.run_event(
  File "/usr/local/lib/python3.8/site-packages/mkdocs/plugins.py", line 520, in run_event
    result = method(item, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/mkdocs_glightbox/plugin.py", line 106, in on_page_content
    html = pattern.sub(
  File "/usr/local/lib/python3.8/site-packages/mkdocs_glightbox/plugin.py", line 107, in <lambda>
    lambda match: self.wrap_img_with_anchor(
  File "/usr/local/lib/python3.8/site-packages/mkdocs_glightbox/plugin.py", line 129, in wrap_img_with_anchor
    src = re.search(r"src=[\"\']([^\"\']+)", img_attr).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```
Thank you for any help!! :)

**Comment by blueswen** [comment]
Apologies for any inconvenience caused. The latest version (v0.3.4) of the plugin has addressed this issue, and if any other wrapping errors occur, a warning log will be generated instead of causing the build to fail.
